---
title: "eds 212 day 2 tasks"
author: "Victoria Cutler"
date: "2022-08-02"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(palmerpenguins)
```

section 3 A
```{r}
exp_1 = expression(x^2)
my_deriv_1 = D(exp_1, "x")
my_deriv_1
x <- 3
eval(my_deriv_1)
```

section 3 B
```{r}
ex_2 = expression(2 * (3 * a + 2)^4 -5)
my_deriv_2 = D(ex_2, "a")
my_deriv_2
a <- 1.2
eval(my_deriv_2)
```

Section 3 C
```{r}
ex_3 = expression((-4 * t)/(t^2 + 1)^3)
my_deriv_3 = D(ex_3, "t")
my_deriv_3
t <- 0
eval(my_deriv_3)
```

Section 4

ggplot
```{r}
ggplot(data = penguins, aes(x = bill_length_mm, y = bill_depth_mm)) +
  geom_point(aes(color = species)) +
  labs(x = "Bill Length (mm)", 
       y = "Bill Depth (mm)", 
       title = "Bill Length vs. Bill Depth") +
  theme_minimal()
```

jitterplot
```{r}
ggplot(data = penguins, aes(x = species, y = flipper_length_mm)) +
  geom_jitter() +
  labs(title = "Species vs. Flipper Length",
       x = "Species",
       y = "Flipper Length (mm)")
```

